var db = require('../db/config.js');

/* NOTE: IDs are auto-generated by Mongoose */
var userSchema = new db.Schema({
  "username": String,
  "password": String
});

module.exports = db.model("User", userSchema);
